### ISSUE TITLE
Bug na arvore

### ISSUE THREAD

**Issue by isvaldo** [josinaldobarbosa/C#1]
Ela só mostra a metade dela

https://github.com/josinaldobarbosa/C/blob/master/Arvore_de_natal.c

**Comment by josinaldobarbosa** [comment]
qual o tamanho da arvore você coloco?

**Comment by isvaldo** [comment]
Tentei 6 , 20 e 100
Em 31/01/2015 22:41, "Josinaldo Albuquerque Barbosa" <
notifications@github.com> escreveu:

**Comment by josinaldobarbosa** [comment]
resolvido
